### ISSUE TITLE
Review #2108312214

### ISSUE THREAD

**Issue by grayherm** [uagpmc/handbook#1]
"USING THIS HANDBOOK"
Consider using you are instead of you're. For me it's easier to read that way. 

"Now, let's get you..." Rewrite "Just navigate to the next chapter by using the link on the very bottom-right of the page." to "Navigate to the bottom-right of the page and click the link to go to the next chapter." 

"ABOUT THE UNIT"
Change  ", we are simply just a bunch of friends who love playing Arma!" to its own sentence. 

"CODE OF CONDUCT"
Add self promotion to third-party advertisement.

"FIRST TIME SETUP"
In the modpack section, try to avoid starting sentences with Because. Thx

**Comment by zuedev** [comment]
Closed with #5
